# Generated by Django 3.2.9 on 2021-12-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('token', models.CharField(max_length=255)),
                ('admin_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('admin_password', models.CharField(max_length=120)),
                ('role', models.BooleanField(verbose_name=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('authorization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('authorization', models.CharField(max_length=255)),
                ('verify', models.BooleanField(verbose_name=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.register')),
            ],
        ),
        migrations.CreateModel(
            name='CrudApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('todo_id', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=8)),
                ('register_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.admin')),
            ],
        ),
    ]
